---
title: "Trabajo practico"
output: html_document
date: '2022-10-03'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rio)
EduExp=import("Education_expenditure.csv")
NoEmploy=import("Unemployment_rate.csv")
```
```{r}
DataFinal=merge(EduExp,NoEmploy, by=c("V1","V2"))
str(DataFinal)
```


```{r}
library(dplyr)
DataFinal=filter(DataFinal, V1!="Country Name")
```

```{r}
colnames(DataFinal)[1]="Country"
colnames(DataFinal)[2]="Code"
colnames(DataFinal)[3]="EduExp"
colnames(DataFinal)[4]="NoEmploy"
```

```{r}
DataFinal$Country[49]="Democratic Republic of the Congo"
DataFinal$Country[50]="Republic of the Congo"
DataFinal$Country[65]="Egypt"
DataFinal$Country[102]="Hong Kong"
DataFinal$Country[112]="Iran"
DataFinal$Country[124]="North Korea"
DataFinal$Country[125]="South Korea"
DataFinal$Country[129]="Laos"
DataFinal$Country[213]="Slovakia"
DataFinal$Country[235]="Syria"
DataFinal$Country[246]="Turkey"
DataFinal$Country[259]="Venezuela"
DataFinal$Country[264]="Yemen"
```

```{r}
library(htmltab)
link = "https://en.wikipedia.org/wiki/Democracy_Index"
path = "/html/body/div[3]/div[3]/div[5]/div[1]/table[5]"
DataWK = htmltab(link, path)
```

```{r}
DataWK$Country=substr(DataWK$Country,star=3,stop=40)
```

```{r}
library(dplyr)
DemoIndex=select(DataWK,Country,"2020")
colnames(DemoIndex)[2]="DemoIndex"
```

```{r}
DemoIndex$Country[91]= substr("Â Â Nepal",start = 5,stop = 9)
DemoIndex$Country[21]= substr("Â Switzerland",start = 3,stop = 13)
DemoIndex$Country[55]="The Gambia"
DemoIndex=arrange(DemoIndex, Country)
```

```{r}
write.csv(DemoIndex,"C:\\Users\\Xande\\OneDrive\\Escritorio\\Estadística II\\Trabajo Practico\\Demo_index", row.names = FALSE)
```

```{r}
library(rio)
GINI=import("C:\\Users\\Xande\\OneDrive\\Escritorio\\Estadística II\\Trabajo Practico\\GINI\\Gini_coeff.csv")
```

```{r}
library(dplyr)
GINI=select(GINI,name,value)
colnames(GINI)[1]="Country"
colnames(GINI)[2]="GINIcoeff"
GINI$Country[158]="Turkey"

GINI=arrange(GINI,Country)
```

```{r}
write.csv(GINI,"C:\\Users\\Xande\\OneDrive\\Escritorio\\Estadística II\\Trabajo Practico\\GINIarreglado", row.names = FALSE)
```

```{r}
dataF=merge(GINI,DataFinal,all=TRUE)
str(dataF)
```
```{r}
dataF2=merge(dataF, DemoIndex,all = TRUE)
str(dataF2)
```
```{r}
dataF3=dataF2[complete.cases(dataF2$GINIcoeff),]
```

```{r}
library(dplyr)
dataF3=select(dataF3, -Code)
```

```{r}
write.csv(dataF3,"C:\\Users\\Xande\\OneDrive\\Escritorio\\Estadística II\\Trabajo Practico\\Data_conjunta_Alex.csv", row.names = FALSE)
```




